### ISSUE TITLE
Use secretKeyRef to expose entire secret to the deployment

### ISSUE THREAD

**Issue by captn3m0** [af-inet/kubestash#2]
It is possible to apply an entire secretRef to a deployment without editing the deployment. 

```
kubectl get secret secrets -n envtest
NAME      TYPE      DATA      AGE
secrets   Opaque    2         3m
```
```
kubectl get deployment nginx-app -n envtest -o json | jq '.spec.template.spec.containers'
[
  {
    "envFrom": [
      {
        "secretRef": {
          "name": "secrets"
        }
      }
    ],
    "image": "nginx",
    "imagePullPolicy": "Always",
    "name": "nginx-app",
    "ports": [
      {
        "containerPort": 80,
        "protocol": "TCP"
      }
    ],
    "resources": {},
    "terminationMessagePath": "/dev/termination-log",
    "terminationMessagePolicy": "File"
  }
]
```
```
kubectl describe secret secret -n envtest
Name:         secrets
Namespace:    envtest
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
HELLO:  14 bytes
WORLD:  11 bytes
```

```
# env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.3.0.1:443
HELLO=nottesting123
```

This way, the deployment won't need frequent edits, and the credstash table can be 1:1 mapped against a secretKeyRef.

So credstash table has `HELLO=1234`, the secretRef will have the same variables, and and deployment gets the entire secret as-is.

**Comment by af-inet** [comment]
@captn3m0 this is awesome!! thank you for sharing, gonna work on an update for this.

**Comment by captn3m0** [comment]
Another plan I had was to have a single kubestash update apply on an entire cluster. 

DynamoDB Table: `credstash-$cluster`
Key: `$namespace/$secretRef/ENV_KEY`

1. Does a credstash getAll to read the entire table and decrypt it
2. Using the above convention scheme, iterates through all the namespaces and sets the correct secrets.

Pro: One single command for the entire cluster, number of tables = number of clusters (so lower cost)

Con: RBAC is harder to implement, since the it can only be run by someone with complete credstash read on that table and write on all namespaces.

I'll be happy to contribute code for this if you think this is a good idea.

**Comment by af-inet** [comment]
@captn3m0 

Regarding the RBAC issue, I've been thinking about automation - so maybe individual users wouldn't actually need to run commands directly. In other words, have `kubestash` run as a daemon which has the appropriate permissions.

[DynamoDB even has a stream API]( https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html). So we could listen for table updates and automatically synchronize it to Kubernetes.

I think that would work well with your namespacing idea !

**Comment by captn3m0** [comment]
I couldn't figure out what would be the right way to do this within kubernetes. The stream API runs a lambda job, which triggers a Job in kubernetes? Then you get additional problems like authenticating to kubernetes itself to trigger a Job.

(I didn't want to run kubestash in lambda)

**Comment by af-inet** [comment]
@captn3m0 I don't think we necessarily need a lambda, the streams API can be read directly without using triggers (we could run in Kubernetes for example).

**Comment by captn3m0** [comment]
@af-inet I was working on a table-sync-to-cluster variant. Can you note down the expected semantics that you'd prefer?

Breaking it down in 3 PRs:

1. Remove `inject` entirely. Just to clean up the codebase
2. Add a `--uppercase` command. Converts lowercase keys in credstash to correct UPPER_CASE environment variables inside kubernetes secrets
3. Add a `pushall` command (need name suggestions) that does a cluster sync depending on the wildcard. With no arguments syncs the entire table, with a namespace argument syncs just that namespace and with a namespace + secret argument only syncs that.

**Comment by af-inet** [comment]
@captn3m0 awesome! can't wait to read it

2. - Would it make more sense to just store UPPER_CASE keys in credstash the same way they're stored in Kubernetes? Not sure what the use case is for the conversion but lmk what you think.

3. - Hmmm, well you're essentially adding the ability to partition / namespace a credstash table.

perhaps `-p --partition` or `could be added to the existing `push` command?

I also went ahead and added `daemon`, which will monitor your table for changes - so if you add this to `push` it can be fully compatible with `daemon`.

**Comment by captn3m0** [comment]
We plan to switch to `UPPER_CASE` keys in credstash, but have multiple apps in place that are using `lower-case` and this would help us immensely. Filed #4 with more details.

Are you okay with removing `inject` related code from the repo?

**Comment by captn3m0** [comment]
Took a look at the daemon implementation, and this might cause issues with dynamoDB rate limits for us.

I'll see if I can do a targeted update of some sort (which would be necessary for partition mode, since all secrets will be sharing the same table and I wouldn't want an update in one to force a complete sync)

**Comment by af-inet** [comment]
@captn3m0 aah I see, that's fine with me in that case.

Lets actually leave `inject` for now since we're  still migrating some apps off of that system at our company.

Regarding `daemon`, yeah let me know if you have an ideas / issues with it. You can tune the `interval` which should reduce your read throughput.

**Comment by af-inet** [comment]
@captn3m0  that also gave me an idea, in `daemon` mode we could optimize credstash reads by only reading modified keys.

**Comment by captn3m0** [comment]
Yup, that is what I meant by targeted update.

I'm facing some issues running kubestash though - It's not picking up the correct kube context. I'm still debugging, will keep you updated (args.context is passed to credstash, and not kube, for one)

**Comment by af-inet** [comment]
@captn3m0 gotcha, yah let me know how it goes

https://github.com/af-inet/kubestash/blob/8d9b5f714b818ca3ff6c7a9ee07017789b1675b5/kubestash/__init__.py#L452

^ might be relevant to that issue

**Comment by af-inet** [comment]
@captn3m0 ooh I see what you mean, there's no support on kubestash for context-selection via the CLI, so I'm assuming kubernetes-python will always load the `current-context`.

**Comment by captn3m0** [comment]
Thanks for the fix.

**Comment by captn3m0** [comment]
Still facing an issue with Auth. I keep getting a 401, likely because we're not using BearerToken auth. Trying to fix

**Comment by af-inet** [comment]
@captn3mo in that case a temporary work around might be too use `kubectl proxy` with `kubestash --proxy`, to skip the auth step

Unfortunate that kubernetes client doesn't yet have feature parity with kubectl

**Comment by captn3m0** [comment]
@af-inet The issue still persists because `--proxy` doesn't seem to be getting honoured.

Looks like it is because you are initializing `kubernetes.client.CoreV1Api()` in 4 different places and the `__init__` for `kubernetes==6.0.0b1` expects a client to be passed (which holds the correct hostname). I'll see if I can fix.

**Comment by captn3m0** [comment]
The documentation at <https://github.com/kubernetes-client/python/issues/303> differs from the implementation now that it is calling `load_kube_config`

**Comment by captn3m0** [comment]
Filed #7 as a fix for this (Can confirm context doesn't get force loaded after this)
